# Cloudflare Workers 설정
# name: 프로젝트명으로 변경 필요
name = "my-app"
main = "workers/app.ts"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./build/client"
binding = "ASSETS"
